use crate::adapters::{DiscoveredModel, TargetFormat, discovery::build_discovered_model_full};

pub fn zai_builtin_models() -> Vec<DiscoveredModel> {
    vec![
        build_discovered_model_full(
            "GLM-5.3".into(),
            Some("GLM-5.3".into()),
            TargetFormat::Anthropic,
            Some(128_000),
            Some(128_000),
        ),
        build_discovered_model_full(
            "GLM-5.3-Flash".into(),
            Some("GLM-5.3-Flash".into()),
            TargetFormat::Anthropic,
            Some(128_000),
            Some(128_000),
        ),
        build_discovered_model_full(
            "GLM-5.2".into(),
            Some("GLM-5.2".into()),
            TargetFormat::Anthropic,
            Some(128_000),
            Some(128_000),
        ),
        build_discovered_model_full(
            "GLM-5-Turbo".into(),
            Some("GLM-5-Turbo".into()),
            TargetFormat::Anthropic,
            Some(128_000),
            Some(128_000),
        ),
        build_discovered_model_full(
            "GLM-5.1".into(),
            Some("GLM-5.1".into()),
            TargetFormat::Anthropic,
            Some(128_000),
            Some(128_000),
        ),
        build_discovered_model_full(
            "GLM-5.1-Highspeed".into(),
            Some("GLM-5.1-Highspeed".into()),
            TargetFormat::Anthropic,
            Some(128_000),
            Some(128_000),
        ),
        build_discovered_model_full(
            "GLM-5V-Turbo".into(),
            Some("GLM-5V-Turbo".into()),
            TargetFormat::Anthropic,
            Some(128_000),
            Some(128_000),
        ),
        build_discovered_model_full(
            "GLM-5".into(),
            Some("GLM-5".into()),
            TargetFormat::Anthropic,
            Some(128_000),
            Some(128_000),
        ),
        build_discovered_model_full(
            "GLM-4.7".into(),
            Some("GLM-4.7".into()),
            TargetFormat::Anthropic,
            Some(128_000),
            Some(128_000),
        ),
        build_discovered_model_full(
            "GLM-4.7-FlashX".into(),
            Some("GLM-4.7-FlashX".into()),
            TargetFormat::Anthropic,
            Some(128_000),
            Some(128_000),
        ),
        build_discovered_model_full(
            "GLM-4.7-Flash".into(),
            Some("GLM-4.7-Flash".into()),
            TargetFormat::Anthropic,
            Some(128_000),
            Some(128_000),
        ),
        build_discovered_model_full(
            "GLM-4.6".into(),
            Some("GLM-4.6".into()),
            TargetFormat::Anthropic,
            Some(128_000),
            Some(128_000),
        ),
        build_discovered_model_full(
            "GLM-4.5-Air".into(),
            Some("GLM-4.5-Air".into()),
            TargetFormat::Anthropic,
            Some(128_000),
            Some(128_000),
        ),
        build_discovered_model_full(
            "GLM-4.5".into(),
            Some("GLM-4.5".into()),
            TargetFormat::Anthropic,
            Some(128_000),
            Some(128_000),
        ),
    ]
}
