#!/usr/bin/env bash
# run-dev.sh — start openproxy (server + web) in background for local testing.
#
# Usage: ./run-dev.sh
#
# Environment overrides (all optional):
#   OPENPROXY_MASTER_KEY   master encryption key for the DB. If unset, a random
#                          one is generated for this run and stored in
#                          .openproxy.env so restarts keep the same DB usable.
#   OPENPROXY_BIND         server bind (default 0.0.0.0:8787)
#   OPENPROXY_WEB_BIND     web bind    (default 0.0.0.0:8788)
#   OPENPROXY_CORE_URL     URL the web uses to reach the server
#                          (default http://127.0.0.1:8787)
#   OPENPROXY_DATA_DIR     where the SQLite DB lives (default ~/.openproxy)

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DATA_DIR="${OPENPROXY_DATA_DIR:-$HOME/.openproxy}"
ENV_FILE="$ROOT_DIR/.openproxy.env"
SERVER_LOG="$ROOT_DIR/openproxy.log"
WEB_LOG="$ROOT_DIR/openproxy-web.log"
SERVER_PID_FILE="$ROOT_DIR/.openproxy.pid"
WEB_PID_FILE="$ROOT_DIR/.web.pid"

mkdir -p "$DATA_DIR"

# --- Master key ---------------------------------------------------------------
# Load all env vars from .openproxy.env (if it exists).
# This picks up OAuth credentials, master key, etc.
if [ -f "$ENV_FILE" ]; then
  # shellcheck disable=SC1090
  . "$ENV_FILE"
fi
if [ -z "${OPENPROXY_MASTER_KEY:-}" ]; then
  OPENPROXY_MASTER_KEY="$(openssl rand -base64 32)"
  cat > "$ENV_FILE" <<EOF
# Generated by run-dev.sh — do not commit.
OPENPROXY_MASTER_KEY=$OPENPROXY_MASTER_KEY
EOF
  echo "[run-dev] generated new OPENPROXY_MASTER_KEY (saved in $ENV_FILE)"
fi
export OPENPROXY_MASTER_KEY

# --- Paths --------------------------------------------------------------------
BIN_SERVER="$ROOT_DIR/target/release/openproxy"
BIN_WEB="$ROOT_DIR/target/release/openproxy-web"
SERVER_BIND="0.0.0.0:8787"
WEB_BIND="0.0.0.0:8788"
CORE_URL="http://127.0.0.1:8787"
export OPENPROXY_WEB_BIND="$WEB_BIND"
export OPENPROXY_CORE_URL="$CORE_URL"

# --- Stop already running instances (idempotent) -----------------------------
for pid_file in "$SERVER_PID_FILE" "$WEB_PID_FILE"; do
  if [ -f "$pid_file" ]; then
    old_pid="$(cat "$pid_file" 2>/dev/null || true)"
    if [ -n "$old_pid" ] && kill -0 "$old_pid" 2>/dev/null; then
      echo "[run-dev] stopping previous process from $pid_file (pid=$old_pid)"
      kill "$old_pid" 2>/dev/null || true
    fi
    rm -f "$pid_file"
  fi
done

# --- Start server -------------------------------------------------------------
echo "[run-dev] starting server on $SERVER_BIND (log: $SERVER_LOG)"
nohup "$BIN_SERVER" >"$SERVER_LOG" 2>&1 &
SERVER_PID=$!
echo "$SERVER_PID" > "$SERVER_PID_FILE"

# --- Start web ----------------------------------------------------------------
echo "[run-dev] starting web on $WEB_BIND -> $CORE_URL (log: $WEB_LOG)"
nohup "$BIN_WEB" >"$WEB_LOG" 2>&1 &
WEB_PID=$!
echo "$WEB_PID" > "$WEB_PID_FILE"

sleep 2

# --- Report -------------------------------------------------------------------
echo
echo "================================================================"
echo " openproxy MVP"
echo "================================================================"
echo " server  pid=$SERVER_PID  http://$SERVER_BIND"
echo " web     pid=$WEB_PID     http://$WEB_BIND"
echo " data    $DATA_DIR"
echo " logs    $SERVER_LOG"
echo "         $WEB_LOG"
echo "================================================================"
echo " Try:"
echo "   curl -s http://$SERVER_BIND/v1/health"
echo "   curl -s http://$SERVER_BIND/v1/models"
echo "   curl -s http://$SERVER_BIND/v1/admin/providers"
echo "   open http://$WEB_BIND"
echo "================================================================"
