-- 000087_provider_prune_models.sql
-- Add prune_models column to providers table:
-- 1: default behavior (upstream models not listed during refresh are deleted, unless pinned in combo_targets)
-- 0: retain discovered models even if temporarily absent from upstream /models (ideal for dynamic/P2P providers like antseed)
ALTER TABLE providers ADD COLUMN prune_models INTEGER NOT NULL DEFAULT 1 CHECK(prune_models IN (0, 1));

-- Disable model pruning for antseed so volatile P2P model lists are retained without breaking combos.
UPDATE providers SET prune_models = 0 WHERE id = 'antseed';

-- Clean up spam model_gone and model_new notifications generated by antseed's P2P fluctuations.
DELETE FROM notifications WHERE provider_id = 'antseed' AND kind IN ('model_gone', 'model_new');
